### ISSUE TITLE
Get this repo prepared for adding to the main awesome list

### ISSUE THREAD

**Issue by dkniffin** [davidhund/awesome-vanilla-js#5]
To get more visibility to this repo, we should get it listed in here: https://github.com/sindresorhus/awesome

There's a few things we'll need to do before that: https://github.com/sindresorhus/awesome/blob/main/awesome.md

- [x] Add the awesome badge to the top (#6)
- [ ] Add a contributor guide (we could copy theirs: https://github.com/sindresorhus/awesome/blob/main/contributing.md) (#8)
- [x] Add a license (they recommend [CC0](https://creativecommons.org/publicdomain/zero/1.0/)) (#8)

**Comment by davidhund** [comment]
Thanks @dkniffin — We might want to update the screenshots in Contributing. Also: I'll look into making you maintainer ;-)

**Comment by dkniffin** [comment]
@davidhund I got the invite, but I was on vacation last week and it seems the invite expired. Mind sending it again now?

**Comment by dkniffin** [comment]
@davidhund Got it that time, thanks! I'll update the screenshots at some point soon, then I think we're ready to make the PR to sindresorhus/awesome
